# Generated by Django 3.2.8 on 2021-10-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('rut', models.CharField(max_length=12, verbose_name='Rut (Sin puntos, con guión)')),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null='true', verbose_name='Fecha Nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=25, null='true', verbose_name='Nacionalidad')),
                ('descripcion', models.CharField(blank=True, max_length=25, null='true', verbose_name='Descripcion')),
                ('nickname', models.CharField(blank=True, max_length=10, null='true', verbose_name='Nickname')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('password', models.CharField(max_length=15, verbose_name='Contraseña')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('archivo', models.IntegerField(blank=True, null='true', verbose_name='Archivo')),
                ('estado', models.CharField(blank=True, max_length=50, null='true', verbose_name='Estado')),
                ('foto', models.ImageField(blank='True', null=True, upload_to='fotos', verbose_name='Fotografia (Opcional)')),
            ],
        ),
    ]
