# Generated by Django 3.2.8 on 2021-10-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0007_alter_paciente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico'),
        ),
    ]
