# Generated by Django 3.2.8 on 2021-10-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0008_alter_paciente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=12, unique=True, verbose_name='Rut (Sin puntos, con guión)'),
        ),
    ]
