# Generated by Django 3.2.8 on 2021-10-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0009_alter_paciente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null='true', verbose_name='Nickname'),
        ),
    ]
