# Generated by Django 3.2.8 on 2021-11-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0010_alter_paciente_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null='true', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=200, null='true', verbose_name='Nacionalidad'),
        ),
    ]
