# Generated by Django 3.2.9 on 2021-11-26 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0013_alter_paciente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
